# Generated by Django 6.0.2 on 2026-03-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boardactivity",
            options={"ordering": ["sequence"]},
        ),
        migrations.AddField(
            model_name="boardactivity",
            name="diff",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="boardactivity",
            name="sequence",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="boardactivity",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="boardactivity",
            name="snapshot",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
