# Generated by Django 6.0.2 on 2026-03-18 11:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0002_alter_boardactivity_options_boardactivity_diff_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boardactivity",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="boardactivity",
            name="diff",
        ),
        migrations.RemoveField(
            model_name="boardactivity",
            name="sequence",
        ),
        migrations.AlterField(
            model_name="boardactivity",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="boardactivity",
            name="snapshot",
            field=models.JSONField(default=list),
        ),
    ]
