# Generated by Django 6.0.2 on 2026-03-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0003_alter_boardactivity_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boardactivity",
            options={"ordering": ["sequence"]},
        ),
        migrations.AddField(
            model_name="boardactivity",
            name="diff",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="boardactivity",
            name="sequence",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="boardactivity",
            name="snapshot",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
